cp original/sec.cpp sec.cpp
cp original/sec.h sec.h
cp original/sha1.cpp sha1.cpp
cp original/sha1.h sha1.h
cp original/utils.cpp utils.cpp
cp original/utils.h utils.h
cp original/nvobridge.cpp nvobridge.cpp
cp original/nvobridge.h nvobridge.h
cp original/main.cpp main.cpp
