cp original/sec_utils.h sec_utils.h
cp original/sec_utils.cpp sec_utils.cpp
cp original/sec_basis.h sec_basis.h
cp original/sec_basis.cpp sec_basis.cpp
cp original/sha1.cpp sha1.cpp
cp original/sha1.h sha1.h
cp original/utils.cpp utils.cpp
cp original/utils.h utils.h
cp original/nvobridge.cpp nvobridge.cpp
cp original/nvobridge.h nvobridge.h
cp original/main.cpp main.cpp
cp original/libdeclare.h libdeclare.h
